version: '3'
name: epo_queue_cp
services:
  queue_api_cp:
    image: epo_queue_cp:latest
    command: python main.py
    ports:
      - "5058:5058"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
      - WORKER_RESULT_TTL=${WORKER_RESULT_TTL}
      - WORKER_FAILURE_TTL=${WORKER_FAILURE_TTL}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"